@startuml Sistema_ListasDeRegalos
left to right direction

actor SoyNovia
actor SoyNovio
actor Invitado

rectangle "Sistema de Listas de Regalos" {
  
  package "Módulo Registro de Usuarios" {
    usecase UC10 as "Registrar usuario"
  }

  package "Módulo Registro de Parejas" {
    usecase UC10a as "Registrar pareja"
  }

  package "Módulo Registro de Invitados" {
    usecase UC10b as "Registrar invitado"
  }

  ' Relaciones jerárquicas
  UC10a -|> UC10
  UC10b -|> UC10

  ' Relaciones con actores
  SoyNovia --> UC10a
  SoyNovio --> UC10a
  Invitado --> UC10b
}

@enduml
