@startuml UC10_RegistrarUsuario
left to right direction
actor Usuario
rectangle "Módulo Registro de Usuarios" {
  usecase UC10 as "Registrar usuario"
  usecase UC10c as "Validar datos"
  usecase UC10d as "Guardar usuario"
  usecase UC10e as "Enviar confirmación"

  UC10 --> UC10c : <<include>>
  UC10 --> UC10d : <<include>>
  UC10 --> UC10e : <<include>>
}
Usuario --> UC10
@enduml
