@startuml UC10b_RegistrarInvitado
left to right direction
actor Invitado

rectangle "Módulo Registro Invitados" {
  usecase UC10b as "Registrar invitado"
  usecase UC10h as "Asignar rol Invitado"

  UC10b --> UC10h : <<include>>
}

Invitado --> UC10b
note right of UC10b
Hereda de UC10 (Registrar usuario)
end note

@enduml
