@startuml modulo_gestion_listas_simple
left to right direction

' === LADO IZQUIERDO ===
actor Pareja
actor SoyNovia
actor SoyNovio 

SoyNovia -|> Pareja #blue
SoyNovio -|> Pareja #blue

' === CENTRO ===
rectangle "Gestión Listas Regalos" {
  usecase UC2 as "Gestionar Lista"
  usecase UC1b as "Crud Lista"
  usecase UC4 as "Buscar Lista"
  usecase UC3 as "Ver Estado"
}

' === LADO DERECHO ===
actor Invitado

' === RELACIONES IZQUIERDA ===
Pareja --> UC2

' === RELACIONES INTERNAS ===
UC1b --|> UC2 #blue
UC4 --|> UC2 #blue
UC3 --|> UC2 #blue
UC2 ..> UC3 #green : include

' === RELACIONES DERECHA ===
Invitado --> UC4 #red
Invitado -left-> UC3 #red

@enduml